from __future__ import annotations

import os
import subprocess
import sys
from getpass import getpass
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent
DISCORD_ENV_PATH = ROOT_DIR / "Discord_scrape" / ".env"
STOAT_ENV_PATH = ROOT_DIR / "Stoat_migration" / ".env"

PACKAGES_TO_INSTALL = [
    "discord.py==2.3.2",
    "aiohttp==3.9.1",
    "python-dotenv==0.19.2",
]


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def write_env(path: Path, values: dict[str, str], header: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [header]
    for key, value in values.items():
        lines.append(f"{key}={value}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ask_value(prompt: str, default: str = "", secret: bool = False) -> str:
    while True:
        if secret and default:
            display = f"{prompt} [current value set]: "
        elif default:
            display = f"{prompt} [{default}]: "
        else:
            display = f"{prompt}: "

        raw = getpass(display) if secret else input(display)
        value = raw.strip()
        if value:
            return value
        if default:
            return default
        print("Value is required.")


def ask_optional_value(prompt: str, default: str = "") -> str:
    if default:
        raw = input(f"{prompt} [{default}]: ").strip()
        return raw if raw else default
    return input(f"{prompt} (optional, press Enter to skip): ").strip()


def ask_message_limit(default: str) -> str:
    while True:
        raw = input(
            "Discord message limit per channel "
            "(none for full history, or positive integer)"
            f" [{default}]: "
        ).strip()
        value = raw if raw else default
        lower = value.lower()
        if lower in {"", "none"}:
            return "none"
        if value.isdigit() and int(value) > 0:
            return value
        print("Invalid value. Use 'none' or a positive integer like 100.")


def ask_yes_no(prompt: str, default_yes: bool = True) -> bool:
    suffix = "[Y/n]" if default_yes else "[y/N]"
    while True:
        raw = input(f"{prompt} {suffix}: ").strip().lower()
        if not raw:
            return default_yes
        if raw in {"y", "yes"}:
            return True
        if raw in {"n", "no"}:
            return False
        print("Please enter y or n.")


def install_dependencies() -> None:
    print("\nInstalling Python packages...")
    cmd = [sys.executable, "-m", "pip", "install", *PACKAGES_TO_INSTALL]
    subprocess.run(cmd, check=True)
    print("Dependencies installed.")


def print_manual_steps() -> None:
    print("\nManual prerequisites (one-time):")
    print("1. Create a Discord bot at https://discord.com/developers/applications")
    print("2. Enable Server Members Intent and Message Content Intent")
    print("3. Invite the Discord bot to your source server(s)")
    print("4. Create a Stoat bot at https://stoat.chat and invite it to target server")
    print("5. Copy your Stoat server ID")


def main() -> int:
    print("Discord -> Stoat setup wizard")
    print("This will create/update:")
    print(f"- {DISCORD_ENV_PATH}")
    print(f"- {STOAT_ENV_PATH}")

    print_manual_steps()

    existing_discord = read_env(DISCORD_ENV_PATH)
    existing_stoat = read_env(STOAT_ENV_PATH)

    default_discord_token = existing_discord.get("DISCORD_TOKEN", "")
    default_limit = existing_discord.get("DISCORD_MESSAGE_LIMIT", "none") or "none"
    default_stoat_token = existing_stoat.get("STOAT_TOKEN", "")
    default_stoat_server = existing_stoat.get("STOAT_SERVER_ID", "")

    print("\nDiscord settings")
    discord_token = ask_value(
        "DISCORD_TOKEN", default=default_discord_token, secret=True
    )
    discord_limit = ask_message_limit(default_limit)

    print("\nStoat settings")
    stoat_token = ask_value("STOAT_TOKEN", default=default_stoat_token, secret=True)
    stoat_server_id = ask_value("STOAT_SERVER_ID", default=default_stoat_server)
    discord_values = {
        "DISCORD_TOKEN": discord_token,
        "DISCORD_MESSAGE_LIMIT": discord_limit,
    }
    stoat_values = {
        "STOAT_TOKEN": stoat_token,
        "STOAT_SERVER_ID": stoat_server_id,
    }

    write_env(DISCORD_ENV_PATH, discord_values, "# Generated by setup.py")
    write_env(STOAT_ENV_PATH, stoat_values, "# Generated by setup.py")

    print("\nEnvironment files updated.")

    if ask_yes_no("Install required Python packages now?", default_yes=True):
        try:
            install_dependencies()
        except subprocess.CalledProcessError as exc:
            print(f"Package install failed with exit code {exc.returncode}.")
            print("Run this manually:")
            print(
                f"  {sys.executable} -m pip install "
                + " ".join(PACKAGES_TO_INSTALL)
            )

    print("\nNext commands:")
    print("1. python Discord_scrape/bot.py")
    print("2. python Stoat_migration/importer.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
